<?php $this->layout()->setTemplate('layout/404'); ?> 


<div class="inner">
 <div class="block" align="center">
	 <a href="http://zaiddabaeen.tk" ><img src="<?php echo $this->basePath('images/shorten_logo.png'); ?>" alt="Shorten" width="20%" style="margin: 0 auto;"/></a>
  <br /><br /><br /><br /><br />
  <span>404</span>
  <p>Sorry. Page not found.</p>
  <p>Did you get lost?</p>
  <p><a href="http://zaiddabaeen.tk" style="color: #FFF">Go back home!</a></p>

 </div>
</div>
