<script>
 $(function() {

  $("#loginBtn").click(function() {
   var btn = $(this);
   $(this).hashForm({
    form: $('#loginForm').serialize(),
    url: "<?php echo $this->url('index', ['action' => 'login']) ?>",
    btn: btn,
    message: "div#message",
    loadingName: "message"
   }).done(function(res) {
    if (res.status == '1') {
     window.location.href = '<?php echo $this->url('index', ['action' => 'manage']) ?>';
    }
   });
  });

 });
</script>

<div class="all-wrapper no-menu-wrapper">
 <div class="login-logo-w" align="center">
  <a href="#" class="logo">
   <img src="<?php echo $this->basePath(); ?>/images/shorten_logo.png" width="100">
  </a>
 </div>
 <br /><br />
 <div class="row">
  <div class="col-md-4 col-md-offset-4">

   <form id="loginForm" method="post" action="" onSubmit="return false;">
    <table class="table table-bordered">
     <tr>
      <td colspan="2" align="center">
       <h3 class="form-title form-title-first" align="center">
	Login
       </h3>
      </td>
     </tr>
     <tr>
      <td>
       Username:
      </td>
      <td>
       <input type="text" name="username" class="form-control">
      </td>
     </tr>
     <tr>
      <td>
       Password:
      </td>
      <td>
       <input type="password" name="password" class="form-control">
      </td>
     </tr>
     <tr>
      <td>
       Keep Logged In:
      </td>
      <td>
		  <input type="checkbox" name="rememberme" class="form-control">
      </td>
     </tr>
     <tr>
      <td colspan="2" align="center">
       <input type="submit" id="loginBtn" class="btn btn-primary" value="Login">
      </td>
     </tr>
     <tr>
      <td colspan="2" align="center">
       <div id="message"></div>
      </td>
     </tr>
    </table>
   </form>

  </div>
 </div>
</div>